package com.javase._31.exceptionhandling;

public class ExceptionHandlingTest03 {

    public static void main(String[] args) {

//        try {
//            // riskli kod
//            // Connection açtık bu işlemde exception fırlatılabilir
//            Connection con = new Connection();
//            con.close();
//        } catch (Exception e) {
//            // catch bloğu
//            con.close();
//            // hem hata durumu hem de çalışan durumu göz önüne aldığımızda hem try hem catch bloğunda connection'u kapattık.
//            // fakat bu durumda duplication yapmış olduk.
//        }
//
//        try {
//            Connection con = new Connection();
//        } catch (Exception e) {
//            //
//        } finally {
//            con.close();
//            // hata olsa da olmasa da finally bloğu çalışacaktırç
//            // catch bloğu çalışsa da çalışmasa da finally bloğu çalışacaktır
//        }
    }
}